import { gql } from "@apollo/client";
import Head from "next/head";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import ListPosts from "../components/listposts/ListPosts";
import FeatGrid from "../components/sections/featGrid/FeatGrid";
import ThreeColGrid from "../components/sections/threecolgrid/ThreeColGrid";
import { client } from "../lib/apollo";

export default function Home({ posts, menu, content }) {


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header menu={menu} />
      <FeatGrid posts={posts} />
      <ListPosts posts={posts} />
      <ThreeColGrid posts={posts} /> */}
      {/* <Footer /> */}
    </div>
  );
}

export async function getStaticProps() {
  const result = await client.query({
    query: gql`
      query PostLists {
        posts(first:20) {
          nodes {
            title
            slug
            modified
            featuredImage {
              node {
                sourceUrl(size: CSCO_MEDIUM)
              }
            }
            excerpt
            categories {
              nodes {
                name
                slug
              }
            }
            author {
              node {
                avatar {
                  url
                }
                name
                slug
              }
            }
          }
        }
        menuItems {
          nodes {
            key: id
            parentId
            title: label
            url
          }
        }
      }
    `,
  });

  return {
    props: {
      menu: result.data.menuItems.nodes,
      posts: result.data.posts.nodes,
    },
    revalidate: 10,
  };
}
